### ISSUE TITLE
Established SSH session has broken colours

### ISSUE THREAD

**Issue by adamnfish** [guardian/ssm-scala#10]
When I ssh onto a box using the `-ssh` flag the colours are broken in the terminal and I need to run `tput sgr0` to fix it. I think this is a problem with the coloured "taint message". It should reset the terminal, not set it to a colour (in this case, black) because you don't know what colours the users terminal / background will be.

**Comment by shtukas** [comment]
Commented on it here: https://github.com/guardian/ssm-scala/pull/9#issuecomment-360152744

**Comment by shtukas** [comment]
Solved here: https://github.com/guardian/ssm-scala/pull/12
