### ISSUE TITLE
Option to provide a machine friendly ssh command

### ISSUE THREAD

**Issue by sihil** [guardian/ssm-scala#20]
I'd like to write a script around this that does `exec $SSHCMD $@` at the end. It's slightly painful to extract $SSHCMD at the moment, an option to only output that would be lovely.

**Comment by aug24** [comment]
How about a switch for ssh only called (say) --bash which would only output the generated ssh command?

You could then do 
export AWS_PROFILE=whatever
ssm ssh -i i-12345678 --bash | bash

**Comment by shtukas** [comment]
+1
tiny detail: assuming we agree that `--bash` is the best command line option to specify it :)

**Comment by sihil** [comment]
Something more akin to `quiet` or `short` would be preferable, rather than something implementation specific. Or even `machine`?

**Comment by shtukas** [comment]
+1 for `machine`

**Comment by shtukas** [comment]
I will make the change later today :)

**Comment by shtukas** [comment]
@sihil @aug24 This should do it :)
https://github.com/guardian/ssm-scala/pull/42
