### ISSUE TITLE
When SSHing get host key from server and enforce use in SSH command

### ISSUE THREAD

**Issue by sihil** [guardian/ssm-scala#73]
At the moment the user must accept the remote host's SSH key when they connect. This should be transparently verified without a user having to deal with it.

The SSM invocation could and should fetch the remote host key (probably `/etc/ssh/ssh_host_ecdsa_key.pub`) and write it to a temporary local host keys file in the correct format (`hostname key_format key`).

The resulting ssh command should then use `UserKnownHostsFile` (to specify the file) and `StrictHostKeyChecking=yes` (`ask` is default, `yes` refuses to connect if the key isn't known) to point at the temporary file and refuse to connect if the host file is not known. e.g.:
```
ssh -o UserKnownHostsFile=/my/tmp/file -o StrictHostKeyChecking=yes <host> etc etc ...
```

This will provide stronger security guarantees as the user will definitely be connecting to the server that SSM has talked to the agent on rather than any MitM.

/cc @adamnfish @shtukas @aug24

**Comment by shtukas** [comment]
+1

**Comment by shtukas** [comment]
Solved in https://github.com/guardian/ssm-scala/pull/84. I am closing this.
