### ISSUE TITLE
--private should be automatic where possible

### ISSUE THREAD

**Issue by sihil** [guardian/ssm-scala#74]
# ISSUE
When sshing to a machine over direct connect `--private` should be applied automatically (especially when the instance has no public IP!)

## Steps to Reproduce
1. ssh to a machine with no public IP

## Actual Results (include screenshots)
If you ssh to a machine without a public IP the command refuses, saying `Found i-07af7c2fc6fd32fc3 but no instances have public IPs (use '--private' if internal address is routable)`.

## Expected Results (include screenshots)
ssm should try to connect to the private IP directly, and _assume_ that it is routable (a socket connect on 22 would be pessimistic but potentially avoid unhelpful timeouts).

**Comment by shtukas** [comment]
@sihil Glancing over the code, that's a easy enough change to do. I actually propose to just drop the `--private ` flag and automatically use the private IP when there isn't a public one. Thoughts ?

**Comment by shtukas** [comment]
Talked with @sihil and just to clarify: "a socket connect on 22 would be pessimistic but potentially avoid unhelpful timeouts" means from the scala code with a short timeout and in the failing case a message to the user saying that the instance has no public address, has one private address, but that private address is not routable. 

In which case, dropping  `--private` is, indeed, the right decision.

**Comment by shtukas** [comment]
Picking this up now. I am not going to drop `--private` (no need to break existing functionalities), but will simply imply it when relevant. The idea around trying to reach port 22 before reporting no routability will come in a different PR.

**Comment by shtukas** [comment]
Addressed in: https://github.com/guardian/ssm-scala/pull/86
