### ISSUE TITLE
Should SSM be a client / server architecture so it can't be subverted?

### ISSUE THREAD

**Issue by sihil** [guardian/ssm-scala#76]
# ISSUE
Anyone can run a modified version of SSM if they so desire.

This means they can remove the tainted command and other stuff.

**Comment by adamnfish** [comment]
I don't think this is a huge problem for us, given the way we work. Additionally, while this is a totally valid observation I don't think solving that is a goal for this project. Good to mention and let's definitely go over this carefully to make sure.

Some observations:

The goals of the tools are to provide the following, which are not impacted by this issue (off the top of my head):
* using temporary credentials for SSH access
* auditability of SSH usage
* transparency of access
* process for approving SSH access to servers
* ensuring people that leave the team / company have their access revoked
* putting SSH behind 2FA

By coupling SSH access to AWS access we solve all the above and more.

The thing is, teams could already have done this themselves - EC2 Run Command has existed for a while. The *value* this program adds is to make it very easy to do the above.

I'd also add that access to the AWS account that grants `ssm` access almost certainly also grants the ability to change more important things. Even if this were switched to a client / server architecture if developers still had access to EC2 Run Command operations they'd be able to do this themselves anyway.

Teams don't have to use SSM. They *do* have to make their use of SSH compliant, and using SSM-Scala is the easiest way to do it. If an empowered team wants to do something different that doesn't use the same taint tagging then that's up to them In the future if we start hanging other functionality off this convention then we can as a department whether we want to mandate or encourage teams to conform.

**Comment by shtukas** [comment]
Unless objection I am going to close this tomorrow as Adam's answer sort of settles the problem :)
