### ISSUE TITLE
"Too many authentication failures"

### ISSUE THREAD

**Issue by sihil** [guardian/ssm-scala#79]
# ISSUE
If you have a lot of keys added to your agent ssm can fail with "Too many authentication failures".

By adding `-o 'IdentitiesOnly yes'` to the ssh command line this issue should go away as it will not use your agent.

**Comment by shtukas** [comment]
Oh Thanks @sihil ! I will include that. ( @adamnfish @aug24  )

**Comment by adamnfish** [comment]
Mad skillz @sihil, thanks

**Comment by shtukas** [comment]
Closing. Solved in: https://github.com/guardian/ssm-scala/pull/84
