### ISSUE TITLE
-B / -b should imply -a

### ISSUE THREAD

**Issue by shtukas** [guardian/ssm-scala#82]
In `ssm ssh -B identity-bastion,identity,PROD -t identity-api-public,identity,CODE -p identity -a -x`

**Comment by aug24** [comment]
You can't use a bastion without using an agent.  So by default, using a bastion should imply using an agent.

For the corner case where an agent is explicitly not wanted, we should provide -A to turn the agent off.

**Comment by shtukas** [comment]
Nice work:
https://github.com/guardian/ssm-scala/commit/2315dc955c1d6cd7d52dbf2fbb8b583fbf1c7c0a

Closing
