### ISSUE TITLE
-A / -a params have opposite meaning to ssh and don't behave the same

### ISSUE THREAD

**Issue by sihil** [guardian/ssm-scala#85]
# ISSUE
In the `ssh` command `-A` enabled agent forwarding whilst `-a` disables it. In `ssm ssh` -a enables agent forwarding and -A doesn't enable forwarding (although in the latter case we don't disable it, we just use whatever the default or `ssh_config` setting is.

It would make more sense to me that these should echo the behaviour of the `ssh` command - principle of least surprise and all that 😄

**Comment by shtukas** [comment]
@aug24

**Comment by aug24** [comment]
I totally agree.  This wasn't designed, just evolved, and it's better to do this before 1.0.0

We should also have minimal effect on people as --bastion and --bastion-tags sets agent to true for you.

**Comment by shtukas** [comment]
See: https://github.com/guardian/ssm-scala/pull/87
