### ISSUE TITLE
raw output doesn't execute correctly

### ISSUE THREAD

**Issue by nicl** [guardian/ssm-scala#90]
# ISSUE

Would like to be able to append to raw output.

## Steps to Reproduce (and result)

    $(ssm ssh --profile discussion -t discussion-api,discussion,PROD --newest --bastion-tags jumphost,discussion,PROD --raw) -L 5432:discussion-aurora-primary-prod.cxtboqhrbtkz.eu-west-1.rds.amazonaws.com:5432
    ssh: Could not resolve hostname yes": nodename nor servname provided, or not known

## Expected Results (include screenshots)

Command works.

thanks @sihil for showing me this!

**Comment by sihil** [comment]
This is due to the nested quotes that are used by proxy command - they are being incorrectly expanded when being executed via raw. Bash escaping makes me sad. I'll try and have a look at it tomorrow.

p.s. are you using bash @nicl?

**Comment by nicl** [comment]
This is resolved now as @sihil figured eval works.
