### ISSUE TITLE
Temporary Keys are world readable

### ISSUE THREAD

**Issue by rahilb** [guardian/ssm-scala#96]
# ISSUE

Temporary ssm keys are written with 0644, so you are unable to use them with `ssh-add`

## Steps to Reproduce

1) Create some temporary keys with ssm, e.g. 
```
ssm ssh --profile identity -t identity-admin,identity,PROD --oldest --bastion-tags identity-bastion,identity,PROD --raw
output: 

ssh -o "IdentitiesOnly yes" -i /private/var/folders/_r/0119p6z94p1d7mktzp05g0n1b00456/T/security_ssm-scala_temporary-rsa-private-key3532330232680684194.tmp -o "UserKnownHostsFile /var/folders/_r/0119p6z94p1d7mktzp05g0n1b00456/T/security_ssm-scala_temporary-host-key8975667675997250957.tmp" -o "StrictHostKeyChecking yes" -o 'ProxyCommand ssh -o "IdentitiesOnly yes" -i /private/var/folders/_r/0119p6z94p1d7mktzp05g0n1b00456/T/security_ssm-scala_temporary-rsa-private-key3532330232680684194.tmp -o "UserKnownHostsFile /var/folders/_r/0119p6z94p1d7mktzp05g0n1b00456/T/security_ssm-scala_temporary-host-key8975667675997250957.tmp" -o "StrictHostKeyChecking yes" -p 22 ubuntu@34.245.96.132 nc 10.248.153.5 22' -t -t ubuntu@10.248.153.5%
```

Now try to add the key to your ssh agent:
`ssh-add -K /var/folders/_r/0119p6z94p1d7mktzp05g0n1b00456/T/*tmp`

And get the error:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/var/folders/_r/0119p6z94p1d7mktzp05g0n1b00456/T/security_ssm-scala_temporary-host-key8975667675997250957.tmp' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Passphrase stored in keychain: /var/folders/_r/0119p6z94p1d7mktzp05g0n1b00456/T/security_ssm-scala_temporary-rsa-private-key3532330232680684194.tmp
Identity added: /var/folders/_r/0119p6z94p1d7mktzp05g0n1b00456/T/security_ssm-scala_temporary-rsa-private-key3532330232680684194.tmp (/var/folders/_r/0119p6z94p1d7mktzp05g0n1b00456/T/security_ssm-scala_temporary-rsa-private-key3532330232680684194.tmp)
```

## Actual Results (include screenshots)

`ssh-add -K /var/folders/_r/0119p6z94p1d7mktzp05g0n1b00456/T/*tmp` fails, as permissions on the temporary private key files are too broad (see error above).

## Expected Results (include screenshots)

`ssh-add -K /var/folders/_r/0119p6z94p1d7mktzp05g0n1b00456/T/*tmp` succeeds. 

The reason for doing this is to allow syntax like `ssh username@myeventualtarget`, with forwarding bastion tunnel config coming from ~/.ssh/config. [The current use case is attaching a java profiler to a remote host](https://www.yourkit.com/docs/java/help/profile_remote_ui.jsp).

**Comment by shtukas** [comment]
Thanks I will correct that today.

**Comment by shtukas** [comment]
So actually, the files are written with the correct permissions, but on @rahilb 's computer _something_ overrides the permissions (maybe of effects of the Enterprise build settings). @rahilb found a solution by adding an additional instruction to his script.
